
export enum PhoenixUIEvent {
    SHOW_UI = 10000,
    CLOSE_UI,
}

export enum PhoenixGameEvent {
    STATE_CHANGE_PREPARE_EVENT = 20000,
    STATE_CHANGE_START_EVENT,
    STATE_CHANGE_PROGRESS_EVENT,
    STATE_CHANGE_END_EVENT,

    UPDATE_SECONDS_EVENT,
    UPDATE_BET_TIEMS_EVENT,

    ADD_BET_MONEY_EVENT,
    SUB_BET_MONEY_EVENT,
    CHOOSE_BET_MONEY_EVENT,

    CHOOSE_BET_TIMES_EVENT,

    UPDATE_PLAYER_INFO_EVENT,
}

export enum PhoenixDataEvent {
    REQ_BET_EVENT = 30000,
    REQ_GET_BACK_EVENT,
    REQ_GET_ALL_BACK_EVENT,

    RSP_BET_EVENT,
    RSP_GET_ITEM_BACK_EVENT,
    RSP_GET_ALL_BACK_EVENT,
    RSP_GET_ROUND_INFO_HISTORY_BACK_EVENT,
    RSP_GET_ONLINE_PLAYER_COUNT_BACK_EVENT,
    RSP_SET_AUTO_CASH_OUT_BACK_EVENT,
    RSP_GET_AUTO_CASH_ALL_BACK_EVENT,
    RSP_GET_BET_RANKING_LIST_BACK_EVENT,
}


